# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Prasiddha Sarma
title: Research Scholar, Tezpur University
email: prasi.s@tezu.ernet.in
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: PrasiddhaSarma
github_username:  prasiddhas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: prasi_s
linkedin_username: prasiddhas
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
 # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/XYZ.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello, This is Prasiddha Sarma, a research scholar under the supervision of Dr. S. Ibotombi Singh in the Department of Computer Science and Engineering, Tezpur University. 
 My area of interests are: <mark>Human Action Recognition</mark>, <mark>Deep Learning</mark>, <mark>Computer Vision</mark> and <mark>Information Retrieval</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Yoga Posture Recognition using Convolutional Neural Networks
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - #title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         This project was associated with the course MCA (Major Project).
        description: | # this will include new lines to allow paragraphs
         I used convolutional neural networks (CNN) to train a model on a dataset of images of 10 different yoga postures, which were collected from Web using scraping methods. The dataset was preprocessed and augmented to increase the model's ability to generalize to new images. I then evaluated the model's performance using metrics such as accuracy, precision, recall, and F1 score.
         This project has potential applications in the development of fitness apps, yoga training programs, and healthcare systems for monitoring and tracking patients' physical rehabilitation progress.
      - layout: top-middle
        title: Delinquency Prediction in Telecom
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - #title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This work dealt with finding the delinquent customer from a telecom service provider database. I was assigned to this project during my Summer Internship period at ICT Academy, IIT Kanpur.
        description: | # this will include new lines to allow paragraphs
         I learnt various Machine Learning frameworks and their implementation strategies for real world problems during the internship period.  
      - layout: top-middle
        title: Solution of Korteweg-De Vries Equations 
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - #title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         Associated with the course M.Sc in Mathematics. This work dealt with finding solutions of Korteweg-De Vries Equations with various parameters.
        description: | # this will include new lines to allow paragraphs
          Aim of this was to investigate the behavior of plasma waves and their interaction with the surrounding medium by solving the Korteweg-de Vries (KdV) equation
          using numerical methods.
     

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deptt. of CSE, Tezpur University
        link: tezu.ernet.in
        # link_text: boringcompany.com
        sub_title: Research Scholar
        caption: September 2020 - Present
        quote: >
         Human Posture Estimation is becoming a spectacular area of research
        description: 
           My work here is to understand the various Human Posture Estimation challenges and to deal with those. Along with these, Teaching Assistant duties are being performed.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pondicherry University
        caption: 2017 - 2020
        sub_title: Master of Computer Applications (MCA)
        quote: > 
         CGPA : 9.55
        
        description: 
         During these 3 years of studies, I have learnt the core and few advanced topics from Computer Science and Applications. I have attended various workshop, seminars in institutes such as IIT Kanpur, IIT Bombay, TIFR Mumbai, University of Hyderabad, Pondicherry Engineering College in this tenure of study.
         Undergone a Summer Internship programme in ICT Academy, IIT Kanpur in the year 2019. Attended MCA Symposium 2018 in NIT Trichy.
  
      - title: Gauhati University
        caption: 2015 - 2017
        sub_title: M.Sc. in Mathematics
        quote: > 
         CGPA : 6.95
        
        description: 
         In this period, I have studied various topics e.g., Real Analysis, Fluid Dynamics, Space Dynamics, Advanced PDE, Astrophysics, Operation Research etc. And able to learn few mathematical concepts relating to Plasma Physics.
      - title: Gauhati University
        caption: 2012 - 2015
        sub_title: B.Sc. in Mathematics
        quote: > 
         Percentage : 63.7
        
        description: 
         Graduated with honours in Mathematics along with Physics and Chemistry as subsidaries.
     
# Footer
#footer_show_references: true
# references_title: (Theme is Collected from : sproogen/resume-theme)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
